### ISSUE TITLE
Search crash when encountering a space

### ISSUE THREAD

**Issue by d3020** [icanzilb/RxSwiftoniOS#1]
Hey Marin, first thank you for this. I find it helpful. Looking forward to your forthcoming post on this too.

I wanted to let you know though, it seems like the app crashes when trying to do a search with a space. For example, "RxSwift MVVM". 
fatal error: unexpectedly found nil while unwrapping an Optional value
on this line
let apiUrl = URL(string: "https://api.github.com/search/repositories?q=" + query)!

**Comment by icanzilb** [comment]
thanks for noticing, the code was built for brevity on the slides, but it makes sense to fix it here in the repo - I pushed a change 👍🏼
